sudo: required
services:
  - docker

before_install:
  - docker build -t apheliont:ci-test -f Dockerfile.dev .

script:
  - docker run apheliont:ci-test npm run test -- --coverage

# deploy:
#   provider: heroku
#   app: apheliont-ci-test
#   api_key:
#     secure: "$api_key"
#   on:
#     branch: master