sudo: required
services:
  - docker

before_install:
  - docker build -t apheliont:ci-test -f Dockerfile.dev .

script:
  - docker run apheliont:ci-test npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "3f9b8af2-c82b-468c-a9eb-ea8be2aac2ae"